name: Close Inactive Jira Issues

on:
  workflow_dispatch:     # manual execution only

jobs:
  close-inactive-jiras:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd jira-glitchtip-issues-closer
          pip install -r requirements.txt

      - name: Close inactive Jira issues
        env:
          MAX_DAYS_OF_INACTIVITY: 7
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          GLITCHTIP_API_TOKEN: ${{ secrets.GLITCHTIP_API_TOKEN }}
        run: |
          cd jira-glitchtip-issues-closer
          python3 close_jiras.py
